import type { NextPage } from 'next'
import Head from 'next/head'
import {Header} from "../components/Header";
import {Login} from "../components/Login";
import {getSession} from "next-auth/react";
import {Sidebar} from "../components/Sidebar";
import {Feed} from "../components/Feed";
import {Widgets} from "../components/Widgets";
import {useCollection} from "react-firebase-hooks/firestore";
import {getFirestore, collection, doc, getDocs, getDoc, onSnapshot, query, orderBy} from "firebase/firestore";
import {db} from "../firebase";
import {PostsType} from "../components/Post";

// @ts-ignore
const Home: NextPage  = ({ session }) => {

  if(!session) return <Login />

  return (
    <div className="bg-gray-100 overflow-y-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*  Header */}
      <Header />
      <main className="flex justify-between overflow-hidden">
        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}
        <Feed />
        {/* Widgets*/}
        <Widgets />
      </main>
    </div>
  )
}

export const getServerSideProps = async (context: any) => {
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}

export default Home
